version: "3.6"

services:
  # Maria DB
  maria:
    image: mariadb:10.5
    container_name: maria
    restart: always
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password','--event_scheduler=ON']
    ports:
      - 3306:3306
    volumes:
      - ./maria/init:/docker-entrypoint-initdb.d
      - ./maria/data:/var/lib/mysql
      - ./maria/backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: aaaaaaaa
  # MQTT broker
  mosquitto:
    image: eclipse-mosquitto
    privileged: true
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    restart: always
  # Redis
  redis:
    image: redis:6.0.6
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "5SWRZc6YRz7ZhcSpaD52bn2zB65w9yBu"]
  # Backend service
  nest:
    build: ./nest
    environment:
      ADDR: '0.0.0.0'
      PORT: 3000
    volumes:
      - ./nest/app:/app
    depends_on:
      - maria
      - mosquitto
      - redis
    ports:
      - 80:3000
      - 443:3001
    restart: always
    command: bash -c "npm install && npm run start"
  # mdev api
  mdev:
    image: golang
    working_dir: /api
    volumes:
     - ./mdev:/api
    ports:
     - 5000:5000
    restart: always
    command: ./phoebe-mdev
